### Edgar Moises Hernandez-Gonzalez
#### 19/11/19-14/12/19
#### Clasificacion de RWE-DWT de MI-EEG con MLP
##### 10 ejecuciones independientes para obtener la media y desviacion estandar

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import cohen_kappa_score, confusion_matrix, precision_recall_fscore_support

In [ ]:
x_train = pd.read_csv("/content/drive/My Drive/BCI-IV-2a/RWE_DWT/MI-EEG-RWE-A09T.csv", header=None)
x_test = pd.read_csv("/content/drive/My Drive/BCI-IV-2a/RWE_DWT/MI-EEG-RWE-A09E.csv", header=None)
y_train = pd.read_csv("/content/drive/My Drive/BCI-IV-2a/RWE_DWT/EtiquetasA09T.csv", header=None)
y_test = pd.read_csv("/content/drive/My Drive/BCI-IV-2a/RWE_DWT/EtiquetasA09E.csv", header=None)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(288, 66)
(288, 66)
(288, 1)
(288, 1)


In [ ]:
#escalar los datos para que tengan media = 0 y desviacion estandar = 1
scaler = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
array_test_acc = []
array_kappa = []
array_precision = []
array_recall = []
array_f1 = []
for i in range(10):
    print("Iteration:", i+1);
    
    clf = MLPClassifier().fit(x_train, y_train)
    test_acc = clf.score(x_test, y_test)
    print('Accuracy:', test_acc)
    array_test_acc.append(test_acc)
    y_pred = clf.predict(x_test)
    kappa = cohen_kappa_score(y_test, y_pred)
    print("kappa: ", kappa)
    array_kappa.append(kappa)
    matriz_confusion = confusion_matrix(y_test, y_pred)
    print("confusion matrix:\n", matriz_confusion)
    metricas = precision_recall_fscore_support(y_test, y_pred, average='macro')
    print(metricas)
    array_precision.append(metricas[0])
    array_recall.append(metricas[1])
    array_f1.append(metricas[2])
    
print()    
print("Resultados:")
print("accuracy:", array_test_acc)
print("kappa:", array_kappa)
print("precision:", array_precision)
print("recall:", array_recall)
print("f1:", array_f1)

Iteration: 1


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.4861111111111111
kappa:  0.31481481481481477
confusion matrix:
 [[32 19 11 10]
 [11 31 15 15]
 [10 10 36 16]
 [ 9  9 13 41]]
(0.48635109864422627, 0.4861111111111111, 0.4848979257975311, None)
Iteration: 2


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.4930555555555556
kappa:  0.32407407407407407
confusion matrix:
 [[34 19 10  9]
 [10 33 18 11]
 [ 8 13 38 13]
 [10  7 18 37]]
(0.4969182027649769, 0.4930555555555556, 0.49352556691084126, None)
Iteration: 3


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.4756944444444444
kappa:  0.30092592592592593
confusion matrix:
 [[33 19  8 12]
 [10 31 18 13]
 [ 9 13 37 13]
 [11 10 15 36]]
(0.47732812972538996, 0.4756944444444444, 0.47573977851257016, None)
Iteration: 4


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.4826388888888889
kappa:  0.31018518518518523
confusion matrix:
 [[37 18 10  7]
 [12 34 16 10]
 [ 9 15 37 11]
 [ 9 10 22 31]]
(0.48862877349730227, 0.4826388888888889, 0.48334249050288125, None)
Iteration: 5


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.4930555555555556
kappa:  0.32407407407407407
confusion matrix:
 [[33 20 11  8]
 [10 37 13 12]
 [ 8 15 36 13]
 [ 8 13 15 36]]
(0.49908882049503667, 0.4930555555555555, 0.4938971474376629, None)
Iteration: 6


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.4791666666666667
kappa:  0.3055555555555556
confusion matrix:
 [[34 19 10  9]
 [12 30 18 12]
 [ 8 10 40 14]
 [12 10 16 34]]
(0.47971955580651227, 0.47916666666666663, 0.47834388861215876, None)
Iteration: 7


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.4722222222222222
kappa:  0.2962962962962963
confusion matrix:
 [[30 21 11 10]
 [ 9 33 18 12]
 [ 8 15 37 12]
 [10  9 17 36]]
(0.4773653898416105, 0.4722222222222222, 0.4723944718574009, None)
Iteration: 8


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.4895833333333333
kappa:  0.3194444444444444
confusion matrix:
 [[35 16 11 10]
 [10 33 14 15]
 [10 16 34 12]
 [ 9 10 14 39]]
(0.4914465798485941, 0.48958333333333326, 0.4899195046145206, None)
Iteration: 9


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5
kappa:  0.33333333333333337
confusion matrix:
 [[31 22 10  9]
 [ 9 35 16 12]
 [11 13 37 11]
 [11  9 11 41]]
(0.5011704525749956, 0.5, 0.499657320638095, None)
Iteration: 10
Accuracy: 0.4826388888888889
kappa:  0.31018518518518523
confusion matrix:
 [[29 24 10  9]
 [10 39 14  9]
 [ 8 16 39  9]
 [11 13 16 32]]
(0.48998920272753566, 0.4826388888888889, 0.48171737799068653, None)

Resultados:
accuracy: [0.4861111111111111, 0.4930555555555556, 0.4756944444444444, 0.4826388888888889, 0.4930555555555556, 0.4791666666666667, 0.4722222222222222, 0.4895833333333333, 0.5, 0.4826388888888889]
kappa: [0.31481481481481477, 0.32407407407407407, 0.30092592592592593, 0.31018518518518523, 0.32407407407407407, 0.3055555555555556, 0.2962962962962963, 0.3194444444444444, 0.33333333333333337, 0.31018518518518523]
precision: [0.48635109864422627, 0.4969182027649769, 0.47732812972538996, 0.48862877349730227, 0.49908882049503667, 0.47971955580651227, 0.4773653898416105, 0.4914465798485941, 0.5011

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [ ]:
print("Mean: %.4f" % np.mean(array_test_acc))
print("std: (+/- %.4f)" % np.std(array_test_acc))
print("kappa: %.4f" % np.mean(array_kappa))
print("std: %.4f" % np.std(array_kappa))
print("precision: %.4f" % np.mean(array_precision))
print("recall: %.4f" % np.mean(array_recall))
print("f1: %.4f" % np.mean(array_f1))

Mean: 0.4854
std: (+/- 0.0082)
kappa: 0.3139
std: 0.0109
precision: 0.4888
recall: 0.4854
f1: 0.4853
