### Edgar Moises Hernandez-Gonzalez
#### 19/11/19-25/11/19
#### Clasificacion de RWE-DWT de MI-EEG con MLP
##### 10 ejecuciones independientes para obtener la media y desviacion estandar

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import cohen_kappa_score, confusion_matrix, precision_recall_fscore_support

In [2]:
x_train = pd.read_csv("MI-EEG-RWE-A01T.csv", header=None)
x_test = pd.read_csv("MI-EEG-RWE-A01E.csv", header=None)
y_train = pd.read_csv("EtiquetasA01T.csv", header=None)
y_test = pd.read_csv("EtiquetasA01E.csv", header=None)

In [3]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(288, 66)
(288, 66)
(288, 1)
(288, 1)


In [4]:
#escalar los datos para que tengan media = 0 y desviacion estandar = 1
scaler = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [5]:
array_test_acc = []
array_kappa = []
array_precision = []
array_recall = []
array_f1 = []
for i in range(10):
    print("Iteration:", i+1);
    
    clf = MLPClassifier().fit(x_train, y_train)
    test_acc = clf.score(x_test, y_test)
    print('Accuracy:', test_acc)
    array_test_acc.append(test_acc)
    y_pred = clf.predict(x_test)
    kappa = cohen_kappa_score(y_test, y_pred)
    print("kappa: ", kappa)
    array_kappa.append(kappa)
    matriz_confusion = confusion_matrix(y_test, y_pred)
    print("confusion matrix:\n", matriz_confusion)
    metricas = precision_recall_fscore_support(y_test, y_pred, average='macro')
    print(metricas)
    array_precision.append(metricas[0])
    array_recall.append(metricas[1])
    array_f1.append(metricas[2])
    
print()    
print("Resultados:")
print("accuracy:", array_test_acc)
print("kappa:", array_kappa)
print("precision:", array_precision)
print("recall:", array_recall)
print("f1:", array_f1)

Iteration: 1


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5173611111111112
kappa:  0.3564814814814815
confusion matrix:
 [[51 11  5  5]
 [36 29  6  1]
 [18  1 32 21]
 [13  2 20 37]]
(0.5481708756045448, 0.5173611111111112, 0.514845413120753, None)
Iteration: 2


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5520833333333334
kappa:  0.4027777777777778
confusion matrix:
 [[45 16  4  7]
 [19 46  6  1]
 [15  1 39 17]
 [17  2 24 29]]
(0.5619314800179527, 0.5520833333333333, 0.5513739068074582, None)
Iteration: 3


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5625
kappa:  0.41666666666666663
confusion matrix:
 [[42 19  4  7]
 [16 48  7  1]
 [12  2 36 22]
 [11  2 23 36]]
(0.5635787790717368, 0.5625, 0.5622824157819295, None)
Iteration: 4


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5486111111111112
kappa:  0.39814814814814814
confusion matrix:
 [[47 13  6  6]
 [27 37  7  1]
 [ 7  1 44 20]
 [14  3 25 30]]
(0.5607057956544478, 0.548611111111111, 0.546680172324233, None)
Iteration: 5


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5069444444444444
kappa:  0.34259259259259256
confusion matrix:
 [[49 14  3  6]
 [29 36  6  1]
 [19  1 30 22]
 [17  3 21 31]]
(0.5282894736842105, 0.5069444444444444, 0.5056381790252759, None)
Iteration: 6


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5520833333333334
kappa:  0.4027777777777778
confusion matrix:
 [[51 12  2  7]
 [25 41  5  1]
 [16  2 31 23]
 [14  3 19 36]]
(0.567300427288616, 0.5520833333333333, 0.5506021762959876, None)
Iteration: 7


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5416666666666666
kappa:  0.38888888888888884
confusion matrix:
 [[46 16  5  5]
 [21 43  7  1]
 [11  3 32 26]
 [13  3 21 35]]
(0.5454321797605379, 0.5416666666666666, 0.5407262027912935, None)
Iteration: 8


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5173611111111112
kappa:  0.3564814814814815
confusion matrix:
 [[42 19  5  6]
 [25 39  7  1]
 [12  1 36 23]
 [12  2 26 32]]
(0.5258745606445236, 0.5173611111111112, 0.5181415534891078, None)
Iteration: 9


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5243055555555556
kappa:  0.3657407407407407
confusion matrix:
 [[52 12  4  4]
 [31 34  6  1]
 [15  2 30 25]
 [13  3 21 35]]
(0.5413499880712995, 0.5243055555555556, 0.5208070660106519, None)
Iteration: 10
Accuracy: 0.5138888888888888
kappa:  0.35185185185185186
confusion matrix:
 [[48 15  2  7]
 [29 36  7  0]
 [20  1 30 21]
 [15  2 21 34]]
(0.5359062980030722, 0.5138888888888888, 0.5137939607439932, None)

Resultados:
accuracy: [0.5173611111111112, 0.5520833333333334, 0.5625, 0.5486111111111112, 0.5069444444444444, 0.5520833333333334, 0.5416666666666666, 0.5173611111111112, 0.5243055555555556, 0.5138888888888888]
kappa: [0.3564814814814815, 0.4027777777777778, 0.41666666666666663, 0.39814814814814814, 0.34259259259259256, 0.4027777777777778, 0.38888888888888884, 0.3564814814814815, 0.3657407407407407, 0.35185185185185186]
precision: [0.5481708756045448, 0.5619314800179527, 0.5635787790717368, 0.5607057956544478, 0.5282894736842105, 0.567300427288616, 0.5454321797605379, 0.5

C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [6]:
print("Mean: %.4f" % np.mean(array_test_acc))
print("std: (+/- %.4f)" % np.std(array_test_acc))
print("kappa: %.4f" % np.mean(array_kappa))
print("precision: %.4f" % np.mean(array_precision))
print("recall: %.4f" % np.mean(array_recall))
print("f1: %.4f" % np.mean(array_f1))

Mean: 0.5337
std: (+/- 0.0188)
kappa: 0.3782
precision: 0.5479
recall: 0.5337
f1: 0.5325
