### Edgar Moises Hernandez-Gonzalez
#### 19/11/19-25/11/19
#### Clasificacion de RWE-DWT de MI-EEG con SVM o Random Forest
##### 10 ejecuciones independientes para obtener la media y desviacion estandar

In [1]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC, LinearSVC
#from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import cohen_kappa_score, confusion_matrix, precision_recall_fscore_support

In [2]:
x_train = pd.read_csv("MI-EEG-RWE-A01T.csv", header=None)
x_test = pd.read_csv("MI-EEG-RWE-A01E.csv", header=None)
y_train = pd.read_csv("EtiquetasA01T.csv", header=None)
y_test = pd.read_csv("EtiquetasA01E.csv", header=None)

In [3]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(288, 66)
(288, 66)
(288, 1)
(288, 1)


In [4]:
#escalar los datos para que tengan media = 0 y desviacion estandar = 1
scaler = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [5]:
array_test_acc = []
array_kappa = []
array_precision = []
array_recall = []
array_f1 = []
for i in range(10):
    print("Iteration:", i+1);
    
    clf = LinearSVC().fit(x_train, y_train)
    #clf = RandomForestClassifier().fit(x_train, y_train)
    test_acc = clf.score(x_test, y_test)
    print('Accuracy:', test_acc)
    array_test_acc.append(test_acc)
    y_pred = clf.predict(x_test)
    kappa = cohen_kappa_score(y_test, y_pred)
    print("kappa: ", kappa)
    array_kappa.append(kappa)
    matriz_confusion = confusion_matrix(y_test, y_pred)
    print("confusion matrix:\n", matriz_confusion)
    metricas = precision_recall_fscore_support(y_test, y_pred, average='macro')
    print(metricas)
    array_precision.append(metricas[0])
    array_recall.append(metricas[1])
    array_f1.append(metricas[2])
    
print()    
print("Resultados:")
print("accuracy:", array_test_acc)
print("kappa:", array_kappa)
print("precision:", array_precision)
print("recall:", array_recall)
print("f1:", array_f1)

Iteration: 1


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5659722222222222
kappa:  0.4212962962962963
confusion matrix:
 [[45 17  4  6]
 [12 51  6  3]
 [ 8  1 29 34]
 [ 6  3 25 38]]
(0.5660992381759694, 0.5659722222222222, 0.5652266442707619, None)
Iteration: 2


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5694444444444444
kappa:  0.42592592592592593
confusion matrix:
 [[45 18  3  6]
 [11 52  6  3]
 [ 8  1 29 34]
 [ 6  3 25 38]]
(0.5687532770866104, 0.5694444444444444, 0.5681233099495291, None)
Iteration: 3


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5694444444444444
kappa:  0.42592592592592593
confusion matrix:
 [[45 17  4  6]
 [12 51  6  3]
 [ 8  1 29 34]
 [ 6  3 24 39]]
(0.5695158416624408, 0.5694444444444444, 0.5684567747067747, None)
Iteration: 4


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5555555555555556
kappa:  0.40740740740740744
confusion matrix:
 [[39 25  2  6]
 [10 53  6  3]
 [ 8  1 29 34]
 [ 5  5 23 39]]
(0.5547319321119478, 0.5555555555555555, 0.5518660444033578, None)
Iteration: 5


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5659722222222222
kappa:  0.4212962962962963
confusion matrix:
 [[45 16  4  7]
 [13 50  6  3]
 [ 9  1 29 33]
 [ 6  3 24 39]]
(0.5666628217162797, 0.5659722222222222, 0.5652595358520565, None)
Iteration: 6


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5694444444444444
kappa:  0.42592592592592593
confusion matrix:
 [[44 18  4  6]
 [10 53  6  3]
 [ 8  1 30 33]
 [ 6  3 26 37]]
(0.56915634378032, 0.5694444444444444, 0.5686271744516983, None)
Iteration: 7


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5590277777777778
kappa:  0.4120370370370371
confusion matrix:
 [[44 18  4  6]
 [14 49  6  3]
 [ 9  1 29 33]
 [ 6  3 24 39]]
(0.5586698782241903, 0.5590277777777778, 0.5579111970592701, None)
Iteration: 8


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5590277777777778
kappa:  0.4120370370370371
confusion matrix:
 [[45 17  3  7]
 [15 48  6  3]
 [ 8  1 29 34]
 [ 6  4 23 39]]
(0.5597779369900642, 0.5590277777777777, 0.5579526815520188, None)
Iteration: 9


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.5798611111111112
kappa:  0.43981481481481477
confusion matrix:
 [[46 14  5  7]
 [11 52  6  3]
 [ 8  1 29 34]
 [ 5  4 23 40]]
(0.5815112899619942, 0.5798611111111112, 0.5794025484166329, None)
Iteration: 10
Accuracy: 0.5625
kappa:  0.41666666666666663
confusion matrix:
 [[43 17  6  6]
 [12 51  6  3]
 [ 8  1 29 34]
 [ 6  3 24 39]]
(0.5633213353454605, 0.5625, 0.5620283955186502, None)

Resultados:
accuracy: [0.5659722222222222, 0.5694444444444444, 0.5694444444444444, 0.5555555555555556, 0.5659722222222222, 0.5694444444444444, 0.5590277777777778, 0.5590277777777778, 0.5798611111111112, 0.5625]
kappa: [0.4212962962962963, 0.42592592592592593, 0.42592592592592593, 0.40740740740740744, 0.4212962962962963, 0.42592592592592593, 0.4120370370370371, 0.4120370370370371, 0.43981481481481477, 0.41666666666666663]
precision: [0.5660992381759694, 0.5687532770866104, 0.5695158416624408, 0.5547319321119478, 0.5666628217162797, 0.56915634378032, 0.5586698782241903, 0.5597779369900642, 0.5815

C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [6]:
print("Mean: %.4f" % np.mean(array_test_acc))
print("std: (+/- %.4f)" % np.std(array_test_acc))
print("kappa: %.4f" % np.mean(array_kappa))
print("precision: %.4f" % np.mean(array_precision))
print("recall: %.4f" % np.mean(array_recall))
print("f1: %.4f" % np.mean(array_f1))

Mean: 0.5656
std: (+/- 0.0067)
kappa: 0.4208
precision: 0.5658
recall: 0.5656
f1: 0.5645
