### Edgar Moises Hernandez-Gonzalez
#### 19/11/19-14/12/19
#### Clasificacion de RWE-DWT de MI-EEG con SVM o Random Forest
##### 10 ejecuciones independientes para obtener la media y desviacion estandar

In [0]:
from google.colab import drive

In [0]:
drive.mount('/content/drive')

In [0]:
import numpy as np
import pandas as pd
#from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import cohen_kappa_score, confusion_matrix, precision_recall_fscore_support

In [0]:
x_train = pd.read_csv("/content/drive/My Drive/BCI-IV-2a/RWE_DWT/MI-EEG-RWE-A09T.csv", header=None)
x_test = pd.read_csv("/content/drive/My Drive/BCI-IV-2a/RWE_DWT/MI-EEG-RWE-A09E.csv", header=None)
y_train = pd.read_csv("/content/drive/My Drive/BCI-IV-2a/RWE_DWT/EtiquetasA09T.csv", header=None)
y_test = pd.read_csv("/content/drive/My Drive/BCI-IV-2a/RWE_DWT/EtiquetasA09E.csv", header=None)

In [0]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(288, 66)
(288, 66)
(288, 1)
(288, 1)


In [0]:
#escalar los datos para que tengan media = 0 y desviacion estandar = 1
scaler = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [0]:
array_test_acc = []
array_kappa = []
array_precision = []
array_recall = []
array_f1 = []
for i in range(10):
    print("Iteration:", i+1);
    
    #clf = LinearSVC().fit(x_train, y_train)
    clf = RandomForestClassifier().fit(x_train, y_train)
    test_acc = clf.score(x_test, y_test)
    print('Accuracy:', test_acc)
    array_test_acc.append(test_acc)
    y_pred = clf.predict(x_test)
    kappa = cohen_kappa_score(y_test, y_pred)
    print("kappa: ", kappa)
    array_kappa.append(kappa)
    matriz_confusion = confusion_matrix(y_test, y_pred)
    print("confusion matrix:\n", matriz_confusion)
    metricas = precision_recall_fscore_support(y_test, y_pred, average='macro')
    print(metricas)
    array_precision.append(metricas[0])
    array_recall.append(metricas[1])
    array_f1.append(metricas[2])
    
print()    
print("Resultados:")
print("accuracy:", array_test_acc)
print("kappa:", array_kappa)
print("precision:", array_precision)
print("recall:", array_recall)
print("f1:", array_f1)

Iteration: 1
Accuracy: 0.3645833333333333
kappa:  0.1527777777777778
confusion matrix:
 [[31 17 15  9]
 [18 22 19 13]
 [13 15 28 16]
 [16  8 24 24]]
(0.36623819416392567, 0.3645833333333333, 0.3635827193148183, None)
Iteration: 2
Accuracy: 0.3368055555555556
kappa:  0.1157407407407407
confusion matrix:
 [[26 22 13 11]
 [16 20 19 17]
 [16 19 29  8]
 [14 17 19 22]]
(0.3398329280872384, 0.3368055555555555, 0.3369545659019344, None)
Iteration: 3
Accuracy: 0.3506944444444444
kappa:  0.1342592592592593
confusion matrix:
 [[25 27  9 11]
 [19 19 12 22]
 [18 10 31 13]
 [17  9 20 26]]
(0.35010751379422267, 0.3506944444444445, 0.35004118931373973, None)
Iteration: 4
Accuracy: 0.375
kappa:  0.16666666666666663
confusion matrix:
 [[26 21 15 10]
 [12 22 19 19]
 [13 16 27 16]
 [ 8 14 17 33]]
(0.37781964958654074, 0.375, 0.3750987101868913, None)
Iteration: 5
Accuracy: 0.3958333333333333
kappa:  0.19444444444444442
confusion matrix:
 [[30 19 14  9]
 [14 15 23 20]
 [13 15 32 12]
 [ 9  6 20 37]]
(0.3902

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff

Accuracy: 0.3541666666666667
kappa:  0.13888888888888884
confusion matrix:
 [[21 28 11 12]
 [12 31 13 16]
 [16 22 21 13]
 [17 10 16 29]]
(0.3543472920522101, 0.35416666666666674, 0.35223902553900716, None)
Iteration: 7
Accuracy: 0.3819444444444444
kappa:  0.17592592592592593
confusion matrix:
 [[24 22 18  8]
 [12 24 20 16]
 [14 15 32 11]
 [ 8 12 22 30]]
(0.38798119380773255, 0.3819444444444445, 0.3821163397019941, None)
Iteration: 8
Accuracy: 0.3541666666666667
kappa:  0.13888888888888884
confusion matrix:
 [[26 26 12  8]
 [12 19 18 23]
 [14 19 32  7]
 [18 11 18 25]]
(0.3553968253968254, 0.35416666666666663, 0.35403089660211334, None)
Iteration: 9
Accuracy: 0.3020833333333333
kappa:  0.06944444444444442
confusion matrix:
 [[27 23 11 11]
 [15 19 20 18]
 [18 18 20 16]
 [17  7 27 21]]
(0.302205878698416, 0.3020833333333333, 0.30170297377505056, None)
Iteration: 10
Accuracy: 0.3472222222222222
kappa:  0.12962962962962965
confusion matrix:
 [[21 24 16 11]
 [10 14 27 21]
 [12 15 31 14]
 [ 4 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff

In [0]:
print("Mean: %.4f" % np.mean(array_test_acc))
print("std: (+/- %.4f)" % np.std(array_test_acc))
print("kappa: %.4f" % np.mean(array_kappa))
print("std: %.4f" % np.std(array_kappa))
print("precision: %.4f" % np.mean(array_precision))
print("recall: %.4f" % np.mean(array_recall))
print("f1: %.4f" % np.mean(array_f1))

Mean: 0.3563
std: (+/- 0.0247)
kappa: 0.1417
std: 0.0329
precision: 0.3577
recall: 0.3563
f1: 0.3549
