### Edgar Moises Hernandez-Gonzalez
#### 27/11/19
#### Clasificacion de alfa de los canales C3 y C4 de MI-EEG con MLP
##### 10 ejecuciones independientes para obtener la media y desviacion estandar

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import cohen_kappa_score, confusion_matrix, precision_recall_fscore_support

In [2]:
x_train = pd.read_csv("MI-EEG-Alfa-A01T.csv", header=None)
x_test = pd.read_csv("MI-EEG-Alfa-A01E.csv", header=None)
y_train = pd.read_csv("EtiquetasA01T.csv", header=None)
y_test = pd.read_csv("EtiquetasA01E.csv", header=None)

In [3]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(288, 510)
(288, 510)
(288, 1)
(288, 1)


In [4]:
#escalar los datos para que tengan media = 0 y desviacion estandar = 1
scaler = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [5]:
array_test_acc = []
array_kappa = []
array_precision = []
array_recall = []
array_f1 = []
for i in range(10):
    print("Iteration:", i+1);
    
    clf = MLPClassifier().fit(x_train, y_train)
    test_acc = clf.score(x_test, y_test)
    print('Accuracy:', test_acc)
    array_test_acc.append(test_acc)
    y_pred = clf.predict(x_test)
    kappa = cohen_kappa_score(y_test, y_pred)
    print("kappa: ", kappa)
    array_kappa.append(kappa)
    matriz_confusion = confusion_matrix(y_test, y_pred)
    print("confusion matrix:\n", matriz_confusion)
    metricas = precision_recall_fscore_support(y_test, y_pred, average='macro')
    print(metricas)
    array_precision.append(metricas[0])
    array_recall.append(metricas[1])
    array_f1.append(metricas[2])
    
print()    
print("Resultados:")
print("accuracy:", array_test_acc)
print("kappa:", array_kappa)
print("precision:", array_precision)
print("recall:", array_recall)
print("f1:", array_f1)

Iteration: 1


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.24305555555555555
kappa:  -0.0092592592592593
confusion matrix:
 [[15 21 22 14]
 [23 21  8 20]
 [24 12 17 19]
 [25 15 15 17]]
(0.24845307760866112, 0.24305555555555558, 0.2449298871776107, None)
Iteration: 2


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.25
kappa:  0.0
confusion matrix:
 [[19 21 15 17]
 [19 23 10 20]
 [23 13 15 21]
 [25 16 16 15]]
(0.25233383015519045, 0.25, 0.2497548150371017, None)
Iteration: 3


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.2465277777777778
kappa:  -0.004629629629629539
confusion matrix:
 [[16 19 10 27]
 [22 22 11 17]
 [26 13 14 19]
 [29 13 11 19]]
(0.25911409071700986, 0.2465277777777778, 0.2486318847189473, None)
Iteration: 4


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.2777777777777778
kappa:  0.03703703703703709
confusion matrix:
 [[19 22 13 18]
 [23 21  7 21]
 [20 14 21 17]
 [25 16 12 19]]
(0.28890544647552163, 0.2777777777777778, 0.28078807111654036, None)
Iteration: 5


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.2534722222222222
kappa:  0.00462962962962965
confusion matrix:
 [[16 20 19 17]
 [21 23  9 19]
 [25 11 19 17]
 [27 16 14 15]]
(0.26010258865012204, 0.2534722222222222, 0.25567535648674655, None)
Iteration: 6


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.2465277777777778
kappa:  -0.004629629629629539
confusion matrix:
 [[16 19 21 16]
 [20 20  7 25]
 [19 16 19 18]
 [19 19 18 16]]
(0.24803187803187804, 0.24652777777777776, 0.24705250563379033, None)
Iteration: 7


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.2743055555555556
kappa:  0.03240740740740744
confusion matrix:
 [[22 21 15 14]
 [20 17 14 21]
 [20 10 25 17]
 [25 16 16 15]]
(0.2748805043440433, 0.2743055555555556, 0.2736673934835655, None)
Iteration: 8


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.28125
kappa:  0.04166666666666663
confusion matrix:
 [[18 18 16 20]
 [16 21 15 20]
 [15 16 21 20]
 [24 13 14 21]]
(0.2832099873296489, 0.28125000000000006, 0.2817833730193727, None)
Iteration: 9


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.2638888888888889
kappa:  0.01851851851851849
confusion matrix:
 [[16 21 19 16]
 [20 21  9 22]
 [19 15 20 18]
 [22 17 14 19]]
(0.2668724925176538, 0.2638888888888889, 0.26486179939874116, None)
Iteration: 10


C:\Users\EdgarMoises\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.2743055555555556
kappa:  0.03240740740740744
confusion matrix:
 [[25 17 11 19]
 [23 24  8 17]
 [31 14 14 13]
 [23 16 17 16]]
(0.27732001359590425, 0.2743055555555556, 0.2715263741401235, None)

Resultados:
accuracy: [0.24305555555555555, 0.25, 0.2465277777777778, 0.2777777777777778, 0.2534722222222222, 0.2465277777777778, 0.2743055555555556, 0.28125, 0.2638888888888889, 0.2743055555555556]
kappa: [-0.0092592592592593, 0.0, -0.004629629629629539, 0.03703703703703709, 0.00462962962962965, -0.004629629629629539, 0.03240740740740744, 0.04166666666666663, 0.01851851851851849, 0.03240740740740744]
precision: [0.24845307760866112, 0.25233383015519045, 0.25911409071700986, 0.28890544647552163, 0.26010258865012204, 0.24803187803187804, 0.2748805043440433, 0.2832099873296489, 0.2668724925176538, 0.27732001359590425]
recall: [0.24305555555555558, 0.25, 0.2465277777777778, 0.2777777777777778, 0.2534722222222222, 0.24652777777777776, 0.2743055555555556, 0.28125000000000006, 0.2638888888

In [6]:
print("Mean: %.4f" % np.mean(array_test_acc))
print("std: (+/- %.4f)" % np.std(array_test_acc))
print("kappa: %.4f" % np.mean(array_kappa))
print("precision: %.4f" % np.mean(array_precision))
print("recall: %.4f" % np.mean(array_recall))
print("f1: %.4f" % np.mean(array_f1))

Mean: 0.2611
std: (+/- 0.0140)
kappa: 0.0148
precision: 0.2659
recall: 0.2611
f1: 0.2619
